global:
  scrape_interval: 1s 

scrape_configs:
  - job_name: 'frontend'
    static_configs:
      - targets: ['host.docker.internal:7298']
  - job_name: 'basketapi'
    static_configs:
      - targets: ['host.docker.internal:5221']
  - job_name: 'catalogapi'
    static_configs:
      - targets: [ 'host.docker.internal:5222' ]
